site_name: kasyachnik
site_description: Telegram bot with Django admin
repo_url: https://github.com/denchip/django_kasyachnik
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/denchip">denchip</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
