# Generated by Django 3.1.4 on 2020-12-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_bet_bets_betsoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_started_bets', to='bot.chat'),
        ),
    ]
