# Generated by Django 3.1.4 on 2020-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_bets_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='betsoption',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
