# Generated by Django 3.1.4 on 2020-12-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_betsoption_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets_obj', to='bot.betsoption'),
        ),
    ]
