# Generated by Django 3.1.4 on 2020-12-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201221_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
